import type { Metadata } from "next";
import { RainbowKitProvider } from "@/components/providers/RainbowKitProvider";

import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <RainbowKitProvider>{children}</RainbowKitProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
